server:
  port: 9011

dubbo:
  application:
    name: search-web
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 3000

# Clear the cache of thymeleaf ,which use to update the data in real time .
spring:
  thymeleaf:
    cache: false