spring:
  data:
    solr:             # ip+port+solr+域名
      host: http://192.168.140.151:8983/solr/mycore

  #  如果不用数据源，那么可以在启动类中使用 注解 @SpringBootApplication(exclude={DataSourceAutoConfiguration.class})
  datasource:
    url: jdbc:mysql://192.168.140.151:3306/qx-v9?characterEncoding=utf8   #  如果想要在数据库中添加中文，要设置characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8.0 以上采用 com.mysql.cj.jdbc.Driver 驱动
    username: root
    password: 123456

server:
  port: 8030

dubbo:
  application:
    name: search-service
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 3000
  protocol:
    port: 20835
