server:
  port: 8060
dubbo:
  application:
    name: dubbo-files
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 3000

## FastDFS
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.140.151:22122