server:
  port: 9010
dubbo:
  application:
    name: back-ground-web
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 3000

# Clear the cache of thymeleaf ,which use to update the data in real time .
spring:
  thymeleaf:
    cache: false

# FastDFS
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.140.151:22122

image:
  server:
    ip: http://192.168.140.151:8080/